# Generated by Django 6.0.3 on 2026-04-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                ("kalori", models.IntegerField()),
                ("miktar", models.CharField(max_length=100)),
                ("aciklama", models.TextField()),
            ],
        ),
    ]
