# Generated by Django 6.0.3 on 2026-04-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="ogun",
            field=models.CharField(
                choices=[
                    ("kahvalti", "Kahvaltı"),
                    ("ogle", "Öğle"),
                    ("aksam", "Akşam"),
                ],
                default="kahvalti",
                max_length=20,
            ),
        ),
    ]
