# Generated by Django 6.0.3 on 2026-04-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0002_meal_ogun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="ogun",
            field=models.CharField(
                choices=[
                    ("kahvalti", "Kahvaltı"),
                    ("ogle", "Öğle"),
                    ("aksam", "Akşam"),
                ],
                max_length=20,
            ),
        ),
    ]
