# Generated by Django 6.0.3 on 2026-04-20 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0003_alter_meal_ogun"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
