# Generated by Django 6.0.3 on 2026-04-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0004_meal_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="karbonhidrat",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="protein",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="yag",
            field=models.IntegerField(default=0),
        ),
    ]
